# pseudo subjective metrics
# -- utmos: UT-MOS score
# -- dnsmos: DNS-MOS score
# -- plcmos: PLC-MOS score
- name: pseudo_mos
  predictor_types: ["utmos", "dnsmos", "plcmos", "singmos"]
  predictor_args:
    utmos:
      fs: 16000
    dnsmos:
      fs: 16000
    plcmos:
      fs: 16000

# An overall model on MOS-bench from Sheet toolkit
# More info in https://github.com/unilight/sheet/tree/main
# --sheet_ssqa: the mos prediction from sheet_ssqa
- name: sheet_ssqa

# torchaudio-squim
# -- torch_squim_pesq: reference-less pesq
# -- torch_squim_stoi: reference-less stoi
# -- torch_squim_si_sdr: reference-less si-sdr
# -- torch_squim_mos: MOS score with reference
- name: squim_no_ref 

# Word error rate with ESPnet-OWSM model
# More model_tag can be from the ESPnet huggingface https://huggingface.co/espnet .
# The default model is `espnet/owsm_v3.1_ebf`.
# NOTE(jiatong): further aggregation are necessary for corpus-level WER/CER
# --owsm_hyp_text: the hypothesis from ESPnet ASR decoding
# --ref_text: reference text (after cleaner)
# --owsm_wer_delete: delete errors
# --owsm_wer_insert: insertion errors
# --owsm_wer_replace: replacement errors
# --owsm_wer_equal: correct matching words/character counts
# --owsm_cer_delete: delete errors
# --owsm_cer_insert: insertion errors
# --owsm_cer_replace: replacement errors
# --owsm_cer_equal: correct matching words/character counts
- name: owsm_wer
  model_tag: default
  beam_size: 5
  text_cleaner: whisper_basic
