config: conf/tuning/train_f5tts.yaml
print_config: false
log_level: INFO
drop_last_iter: false
dry_run: false
iterator_type: sequence
valid_iterator_type: null
output_dir: exp_seen/tts_stats_raw_phn_tacotron_g2p_en_no_space/logdir/stats.29
ngpu: 0
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: null
dist_rank: null
local_rank: null
dist_master_addr: null
dist_master_port: null
dist_launcher: null
multiprocessing_distributed: false
unused_parameters: false
sharded_ddp: false
use_deepspeed: false
deepspeed_config: null
gradient_as_bucket_view: true
ddp_comm_hook: null
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
use_tf32: false
collect_stats: true
write_collected_feats: false
max_epoch: 40
patience: null
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - train
    - loss
    - min
-   - valid
    - loss
    - min
-   - train
    - acc
    - max
-   - valid
    - acc
    - max
keep_nbest_models:
- 10
nbest_averaging_interval: 0
grad_clip: 5.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: false
train_dtype: float32
use_amp: false
log_interval: null
use_matplotlib: true
use_tensorboard: true
create_graph_in_tensorboard: false
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
use_adapter: false
adapter: lora
save_strategy: all
adapter_conf: {}
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 1000000
valid_batch_bins: null
category_sample_size: 10
upsampling_factor: 0.5
category_upsampling_factor: 0.5
dataset_upsampling_factor: 0.5
dataset_scaling_factor: 1.2
max_batch_size: null
min_batch_size: 1
train_shape_file:
- exp_seen/tts_stats_raw_phn_tacotron_g2p_en_no_space/logdir/train.29.scp
valid_shape_file:
- exp_seen/tts_stats_raw_phn_tacotron_g2p_en_no_space/logdir/valid.29.scp
batch_type: folded
valid_batch_type: null
fold_length: []
sort_in_batch: descending
shuffle_within_batch: false
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
chunk_excluded_key_prefixes: []
chunk_default_fs: null
chunk_max_abs_length: null
chunk_discard_short_samples: true
train_data_path_and_name_and_type:
-   - dump/24k/raw/titw_easy_seen_train/text
    - text
    - text
-   - dump/24k/raw/titw_easy_seen_train/wav.scp
    - speech
    - sound
valid_data_path_and_name_and_type:
-   - dump/24k/raw/titw_easy_seen_dev/text
    - text
    - text
-   - dump/24k/raw/titw_easy_seen_dev/wav.scp
    - speech
    - sound
multi_task_dataset: false
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
allow_multi_rates: false
valid_max_cache_size: null
exclude_weight_decay: false
exclude_weight_decay_conf: {}
optim: adadelta
optim_conf: {}
scheduler: null
scheduler_conf: {}
token_list:
- <blank>
- <unk>
- T
- N
- AH0
- D
- S
- R
- L
- IH1
- DH
- K
- AY1
- M
- W
- Z
- AH1
- AE1
- EH1
- UW1
- IH0
- IY1
- V
- AA1
- B
- ','
- OW1
- F
- P
- IY0
- AO1
- HH
- NG
- ER0
- EY1
- .
- Y
- G
- TH
- AW1
- JH
- SH
- UH1
- CH
- ER1
- EY2
- OW0
- IH2
- AH2
- OY1
- EH2
- AA2
- AY2
- OW2
- '?'
- EH0
- UW0
- ZH
- '...'
- AY0
- AE2
- AE0
- AO2
- AA0
- IY2
- AO0
- UW2
- UH2
- AW2
- ER2
- EY0
- AW0
- UH0
- ''''
- OY2
- '... ...'
- '!'
- OY0
- ..
- <sos/eos>
odim: null
model_conf: {}
use_preprocessor: true
token_type: phn
bpemodel: null
non_linguistic_symbols: null
cleaner: tacotron
g2p: g2p_en_no_space
feats_extract: fbank
feats_extract_conf:
    fs: 24000
    n_mels: 100
    n_fft: 1024
    hop_length: 256
    win_length: 1024
    fmin: 80
    fmax: 7600
normalize: null
normalize_conf: {}
tts: f5tts_espnet
tts_conf:
    pretrained_ckpt: /work/nvme/bbjs/ttao3/espnet/egs2/libritts_r/tts2/downloads/F5-TTS/F5TTS_v1_Base/model_1250000.safetensors
    model_cfg: F5TTS_v1_Base
    use_ema: true
    mel_spec_kwargs:
        n_fft: 1024
        hop_length: 256
        win_length: 1024
        n_mel_channels: 100
        target_sample_rate: 24000
        mel_spec_type: vocos
pitch_extract: null
pitch_extract_conf:
    fs: 24000
    n_fft: 1024
    hop_length: 256
    f0max: 400
    f0min: 80
pitch_normalize: null
pitch_normalize_conf: {}
energy_extract: null
energy_extract_conf:
    fs: 24000
    n_fft: 1024
    hop_length: 256
    win_length: 1024
energy_normalize: null
energy_normalize_conf: {}
required:
- output_dir
- token_list
version: '202509'
distributed: false
